### ISSUE TITLE
This needs a license

### ISSUE THREAD

**Issue by skunkiferous** [sbarzowski/jsonnet-parser-combinators#1]
Hi. I just found this, Seems interesting.

But I'm not touching anything that hasn't got an explicit license
(as should any sensible dev, that wants to stay out of trouble).

Would you mind spending the 2 minutes (after you made up your mind about which one to use)
required to add a license to your repo? For example, Apache, like jsonnet itself...

**Comment by sbarzowski** [comment]
Fair enough, done.
